version: '3.8'

services:
   postgres:
      image: postgres:15
      environment:
         POSTGRES_DB: cherry_db
         POSTGRES_USER: cherry_user
         POSTGRES_PASSWORD: cherry_password
      volumes:
         - postgres_data:/var/lib/postgresql/data
      ports:
         - '5432:5432'
      healthcheck:
         test: ['CMD-SHELL', 'pg_isready -U cherry_user -d cherry_db']
         interval: 10s
         timeout: 5s
         retries: 5

   backend:
      build:
         context: ./service
         dockerfile: Dockerfile
      environment:
         DATABASE_URL: jdbc:postgresql://postgres:5432/cherry_db
         DATABASE_USERNAME: cherry_user
         DATABASE_PASSWORD: cherry_password
      ports:
         - '8080:8080'
      depends_on:
         postgres:
            condition: service_healthy

   frontend:
      build:
         context: ./client
         dockerfile: Dockerfile
      environment:
         VITE_API_URL: http://localhost:8080
      ports:
         - '5173:5173'
      depends_on:
         - backend

volumes:
   postgres_data:
