services:
   backend-service:
      build:
         context: ./service
         dockerfile: Dockerfile
      environment:
         APPLICATION_ENVIRONMENT: production
         DATABASE_MIGRATION_MODE: ${DATABASE_MIGRATION_MODE}
         DATABASE_URL: ${DATABASE_URL}
         DATABASE_USERNAME: ${DATABASE_USERNAME}
         DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      ports:
         - '8080:8080'
      networks:
         - app-network

   client-service:
      build:
         context: ./client
         dockerfile: Dockerfile
      environment:
         NODE_ENV: production
         VITE_API_URL: http://backend-service:8080
      ports:
         - '3000:3000'
      depends_on:
         - backend-service
      networks:
         - app-network

volumes:
   postgres_data:

networks:
   app-network:
      driver: bridge
